<?php

namespace AppBundle\Repository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * counts all actions by a certain survey id
     * @param $id
     * @return array
     */
    public function countActionBySurveyId($id){
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder()
                ->select('COUNT(a.id) as count')
                ->from('AppBundle:Action', 'a')
                ->where('a.answersId = :answerID')
                ->setParameter('answerID', $id);

            return $query->getQuery()->getResult();
    }
}
