<?php

namespace AppBundle\Repository;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnswerId($surveyID, $buttonID) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('a.id')
            ->from('AppBundle:Answers', 'a')
            ->where('a.surveyId = :surveyID')
            ->andWhere('a.buttonId = :buttonID')
            ->setParameter('surveyID', $surveyID)
            ->setParameter('buttonID', $buttonID);

        return $query->getQuery()->getArrayResult();
    }

    public function getAnswerOption($surveyID) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('a.answerOption')
            ->from('AppBundle:Answers', 'a')
            ->where('a.surveyId = :surveyID')
            ->setParameter('surveyID', $surveyID)
            ->orderBy('a.buttonId', 'ASC');

        return $query->getQuery()->getArrayResult();

//        print_r($result);
//        $answerOption = array();
//        for($i = 0; $i< count($result); $i++) {
//            $answerOption = $result[$i]["answerOption"];
//        }
//
//        print_r($answerOption);


    }
}
