<?php

namespace AppBundle\Repository;

/**
 * ButtonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ButtonsRepository extends \Doctrine\ORM\EntityRepository
{
}
