<?php

namespace AppBundle\Repository;

/**
 * DevicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevicesRepository extends \Doctrine\ORM\EntityRepository
{
}
