<?php

namespace AppBundle\Repository;

/**
 * RanksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RanksRepository extends \Doctrine\ORM\EntityRepository
{
}
