<?php

namespace AppBundle\Repository;

/**
 * Survey_ActiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Survey_ActiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQuestion($conn, $time) {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('sa', 's.buttonQuantity as buttonQuantity', 's.question as question', 's.id as surveyID')
            ->from('AppBundle:Survey_Active', 'sa')
            ->leftJoin('AppBundle:Survey', 's', 'WITH', 'sa.surveyId = s.id')
            ->leftJoin('AppBundle:Devices', 'd', 'WITH', 'sa.devicesId = d.id')
            ->where('d.conn = :conn', 'sa.start <= :time', 'sa.end > :time')
            ->setParameter('conn' , $conn)
            ->setParameter('time', $time)
            ->getQuery();

        return $query;
    }
}
