AppBundle\Entity\Action:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ActionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        answerId:
            type: integer
            column: answer_id
        devicesId:
            type: integer
            column: devices_id
        time:
            type: datetime
    lifecycleCallbacks: {  }
