AppBundle\Entity\Buttons:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ButtonsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        buttons:
            type: string
            length: '45'
    lifecycleCallbacks: {  }
