AppBundle\Entity\Devices:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DevicesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        connection:
            type: string
            length: 255
    lifecycleCallbacks: {  }
