AppBundle\Entity\Survey_Active:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Survey_ActiveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        surveyId:
            type: integer
            column: survey_id
        devicesId:
            type: integer
            column: devices_id
        start:
            type: datetime
        end:
            type: datetime
    lifecycleCallbacks: {  }
