AppBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '64'
        password:
            type: string
            length: 255
        rank:
            type: integer
    lifecycleCallbacks: {  }
